# Generated by Django 4.2.7 on 2023-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_status_remove_category_trending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rpm',
            field=models.CharField(max_length=15),
        ),
    ]
