# Generated by Django 4.2.7 on 2023-11-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_category_image_remove_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='id_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
