# Generated by Django 4.2.7 on 2023-11-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_repaired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
