# Generated by Django 4.2.7 on 2023-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='armature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='brush',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stator',
            field=models.BooleanField(default=False),
        ),
    ]
