# Generated by Django 4.2.7 on 2023-11-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_armature_product_brush_product_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='armature',
            field=models.BooleanField(default=False, verbose_name='is_armature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brush',
            field=models.BooleanField(default=False, verbose_name='is_brush'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.BooleanField(default=False, verbose_name='is_frame'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stator',
            field=models.BooleanField(default=False, verbose_name='is_stator'),
        ),
    ]
