# Generated by Django 5.0 on 2023-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_description_alter_product_rpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ampere',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='efficiency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vibration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
