# Generated by Django 5.0 on 2023-12-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_ampere_product_efficiency_product_vibration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='efficiency',
        ),
    ]
